### ISSUE TITLE
black screen when activate the module

### ISSUE THREAD

**Issue by Robiv8** [0m4r/MMM-euro2024#1]
I get a black screen when I activate the module?
Original Config as in description and token available.

**Comment by 0m4r** [comment]
hi @Robiv8 can you provide me with some logs?
Can you see any errors? I need a bit more information in order to be able to help you :D

**Comment by Robiv8** [comment]
OK Sorry, das log sagt: Please correct syntax errors at or above this line: ReferenceError: b1e6..meinToken..67c8c5 is not defined
Danke

**Comment by 0m4r** [comment]
answered on the magic mirror forum, hence closing.
