### ISSUE TITLE
Results not displayed

### ISSUE THREAD

**Issue by mirko3000** [0m4r/MMM-euro2024#3]
Hi there,
results are not getting displayed due to an error in your scripts:
Line 92:
`tr.appendChild(buildTD(m.score.fullTime.homeTeam, 'MMM-euro2024-score'));`

This should be:
`tr.appendChild(buildTD(m.score.fullTime.home, 'MMM-euro2024-score'));`

Same for the away team.

Else: nice work!

**Comment by 0m4r** [comment]
@mirko3000 thanks for reporting this bug.
it should be now fixed in version 1.0.6 :)
